# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Bash@3
  displayName: Install project dependencies.
  inputs:
    targetType: 'inline'
    script: |
     npm install

- task: Bash@3
  displayName: Install Snyk CLI
  inputs:
    targetType: inline
    script: |
      npm install snyk --location=global
      echo "##vso[task.setvariable variable=snyk;]$(which snyk)"
      
- task: Bash@3
  displayName: Install Snyk-To-HTML
  inputs:
    targetType: inline
    script: |
      npm install snyk-to-html --location=global
      echo "##vso[task.setvariable variable=snyk-to-html;]$(which snyk-to-html)"
      
- task: Bash@3
  displayName: Authenticate Snyk and create report directory.
  with:
    snyk_poc_token: ${{secrets.snyk_poc_token}}
  inputs:
    targetType: inline
    script: |
      $(snyk) auth "$snyk_poc_token"
      mkdir snyk-scan-results

- task: Bash@3
  displayName: Run Snyk dependency scan and generate HTML report.
  inputs:
    targetType: inline
    script: |
      $(snyk) test --all-projects --json | $(snyk-to-html) -o snyk-scan-results/snyk-dependency-scan-results.html

- task: Bash@3
  displayName: Run Snyk code scan and generate HTML report.
  inputs:
    targetType: inline
    script: |
      $(snyk) code test --json | $(snyk-to-html) -o snyk-scan-results/snyk-code-scan-results.html
      
- task: PublishPipelineArtifact@1
  displayName: Publish Snyk scan reports to artifacts.
  inputs:
    targetPath: snyk-scan-results
    artifactName: snyk-scan-results

